# Edit headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    
# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "dist"

  # Default build command.
  command = "npm run generate"

  # Directory with the serverless Lambda functions to deploy to AWS.
  functions = "./functions"

[[plugins]]
	package = "@netlify/plugin-sitemap"
