export default `
    query AllSlugs{
        allPages{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        allModularPages{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        contact{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        team{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        portfolio{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        investorsPage{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        allFunds{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        useCasesPage{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        podcastsPage{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        pressRoom{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        sustainableEngagement{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        },
        ring2success{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        },
        vision{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
    }
`;
