export default `
    query AllSlugs{
        allModulars(first: 100){
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        allFunds{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        mediaList{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        portfolioList{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        contact{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
        team{
            _modelApiKey
            _allSlugLocales{
                locale
                value
            }
        }
    }
`;
